server:
  port: 9001

spring:
  application:
    name: user-serviec1

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka